version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx_balanceador
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - servidor1
      - servidor2
      - servidor3
    networks:
      - red_proyectof

  servidor1:
    build: 
      context: ./servidor1
      dockerfile: Dockerfile
    container_name: servidor1
    networks:
      - red_proyectof

  servidor2:
    build:
      context: ./servidor2
      dockerfile: Dockerfile
    container_name: servidor2
    networks:
      - red_proyectof

  servidor3:
    build:
      context: ./servidor3
      dockerfile: Dockerfile
    container_name: servidor3
    networks:
      - red_proyectof

networks:
  red_proyectof:
    external: true


